# Parameters for data engineering
data_engineering:
  dataset_handle: "mirichoi0218/insurance"
  temp_download_path: "data/temp_kaggle"

# Parameters for data processing
data_processing:
  classification_threshold_method: "median" # or "mean", or a specific value

# Parameters for model regression
model_regression:
  test_size: 0.2
  random_state: 42

# Parameters for model classification
model_classification:
  test_size: 0.2
  random_state: 42
  logistic_regression:
    max_iter: 1000
  random_forest:
    param_grid:
      n_estimators: [50, 100, 200]
      max_depth: [null, 10, 20] # null in YAML maps to None in Python
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2]
  xgboost:
    param_grid:
      n_estimators: [100, 200, 300]
      max_depth: [3, 5, 7]
      learning_rate: [0.05, 0.1]
      subsample: [0.8, 1.0]
    eval_metric: "logloss"
  svc:
    param_grid:
      C: [0.1, 1, 10]
      gamma: ["scale", "auto", 0.1, 1]
    probability: true
  grid_search:
    cv: 5
    n_jobs: -1
    verbose: 0